// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// meanMASE
double meanMASE(NumericVector x, double meanNB);
RcppExport SEXP _ATAforecasting_meanMASE(SEXP xSEXP, SEXP meanNBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type meanNB(meanNBSEXP);
    rcpp_result_gen = Rcpp::wrap(meanMASE(x, meanNB));
    return rcpp_result_gen;
END_RCPP
}
// meanIT
double meanIT(NumericVector x, int t);
RcppExport SEXP _ATAforecasting_meanIT(SEXP xSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(meanIT(x, t));
    return rcpp_result_gen;
END_RCPP
}
// AutoATACore
double AutoATACore(NumericVector IAZ, int IZP, int IZQ, double IZPHI, int IZMO, int IZAC, int IZIL, int IZIT, NumericVector IZTA_0, NumericVector IZTM_0);
RcppExport SEXP _ATAforecasting_AutoATACore(SEXP IAZSEXP, SEXP IZPSEXP, SEXP IZQSEXP, SEXP IZPHISEXP, SEXP IZMOSEXP, SEXP IZACSEXP, SEXP IZILSEXP, SEXP IZITSEXP, SEXP IZTA_0SEXP, SEXP IZTM_0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type IAZ(IAZSEXP);
    Rcpp::traits::input_parameter< int >::type IZP(IZPSEXP);
    Rcpp::traits::input_parameter< int >::type IZQ(IZQSEXP);
    Rcpp::traits::input_parameter< double >::type IZPHI(IZPHISEXP);
    Rcpp::traits::input_parameter< int >::type IZMO(IZMOSEXP);
    Rcpp::traits::input_parameter< int >::type IZAC(IZACSEXP);
    Rcpp::traits::input_parameter< int >::type IZIL(IZILSEXP);
    Rcpp::traits::input_parameter< int >::type IZIT(IZITSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type IZTA_0(IZTA_0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type IZTM_0(IZTM_0SEXP);
    rcpp_result_gen = Rcpp::wrap(AutoATACore(IAZ, IZP, IZQ, IZPHI, IZMO, IZAC, IZIL, IZIT, IZTA_0, IZTM_0));
    return rcpp_result_gen;
END_RCPP
}
// AutoATADamped
NumericVector AutoATADamped(NumericVector IAX, int IXP, int IXQ, int IXMO, int IXAC, int IXLF, int IXTF, double IXPHIS, double IXPHIE, double IXPHISS, int IXIL, int IXIT, NumericVector IXTA_0, NumericVector IXTM_0);
RcppExport SEXP _ATAforecasting_AutoATADamped(SEXP IAXSEXP, SEXP IXPSEXP, SEXP IXQSEXP, SEXP IXMOSEXP, SEXP IXACSEXP, SEXP IXLFSEXP, SEXP IXTFSEXP, SEXP IXPHISSEXP, SEXP IXPHIESEXP, SEXP IXPHISSSEXP, SEXP IXILSEXP, SEXP IXITSEXP, SEXP IXTA_0SEXP, SEXP IXTM_0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type IAX(IAXSEXP);
    Rcpp::traits::input_parameter< int >::type IXP(IXPSEXP);
    Rcpp::traits::input_parameter< int >::type IXQ(IXQSEXP);
    Rcpp::traits::input_parameter< int >::type IXMO(IXMOSEXP);
    Rcpp::traits::input_parameter< int >::type IXAC(IXACSEXP);
    Rcpp::traits::input_parameter< int >::type IXLF(IXLFSEXP);
    Rcpp::traits::input_parameter< int >::type IXTF(IXTFSEXP);
    Rcpp::traits::input_parameter< double >::type IXPHIS(IXPHISSEXP);
    Rcpp::traits::input_parameter< double >::type IXPHIE(IXPHIESEXP);
    Rcpp::traits::input_parameter< double >::type IXPHISS(IXPHISSSEXP);
    Rcpp::traits::input_parameter< int >::type IXIL(IXILSEXP);
    Rcpp::traits::input_parameter< int >::type IXIT(IXITSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type IXTA_0(IXTA_0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type IXTM_0(IXTM_0SEXP);
    rcpp_result_gen = Rcpp::wrap(AutoATADamped(IAX, IXP, IXQ, IXMO, IXAC, IXLF, IXTF, IXPHIS, IXPHIE, IXPHISS, IXIL, IXIT, IXTA_0, IXTM_0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ATAforecasting_meanMASE", (DL_FUNC) &_ATAforecasting_meanMASE, 2},
    {"_ATAforecasting_meanIT", (DL_FUNC) &_ATAforecasting_meanIT, 2},
    {"_ATAforecasting_AutoATACore", (DL_FUNC) &_ATAforecasting_AutoATACore, 10},
    {"_ATAforecasting_AutoATADamped", (DL_FUNC) &_ATAforecasting_AutoATADamped, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_ATAforecasting(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
