# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

outMASE <- function(insmp, outsmp, frcst, frqx) {
    .Call(`_ATAforecasting_outMASE`, insmp, outsmp, frcst, frqx)
}

inMASE <- function(insmp, fitsmp, frqx) {
    .Call(`_ATAforecasting_inMASE`, insmp, fitsmp, frqx)
}

meanIT <- function(x, t) {
    .Call(`_ATAforecasting_meanIT`, x, t)
}

AutoATACore <- function(IAZ, IZP, IZQ, IZPHI, IZMO, IZAC, IZIL, IZIT, IZTA_0, IZTM_0, IZFRQ) {
    .Call(`_ATAforecasting_AutoATACore`, IAZ, IZP, IZQ, IZPHI, IZMO, IZAC, IZIL, IZIT, IZTA_0, IZTM_0, IZFRQ)
}

AutoATADamped <- function(IAX, IXP, IXQ, IXMO, IXAC, IXLF, IXTF, IXPHIS, IXPHIE, IXPHISS, IXIL, IXIT, IXTA_0, IXTM_0, IXFRQ) {
    .Call(`_ATAforecasting_AutoATADamped`, IAX, IXP, IXQ, IXMO, IXAC, IXLF, IXTF, IXPHIS, IXPHIE, IXPHISS, IXIL, IXIT, IXTA_0, IXTM_0, IXFRQ)
}

AutoATA <- function(IAX, IXP, IXQ, IXMO, IXAC, IXLF, IXTF, IXPHIS, IXPHIE, IXPHISS, IXIL, IXIT, IXTA_0, IXTM_0, IXSMO, IXST, max_smo, max_st, LENX, IXFRQ) {
    .Call(`_ATAforecasting_AutoATA`, IAX, IXP, IXQ, IXMO, IXAC, IXLF, IXTF, IXPHIS, IXPHIE, IXPHISS, IXIL, IXIT, IXTA_0, IXTM_0, IXSMO, IXST, max_smo, max_st, LENX, IXFRQ)
}

